apiVersion: v1
kind: Service
metadata:
  name: face-image-input-api-service
  labels:
    app: face-image-input-api
spec:
  ports:
  - protocol: TCP
    port: 80
  selector:
    app: face-image-input-api
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: face-image-input-api
  name: face-image-input-api
spec:
  replicas: 10
  selector:
    matchLabels:
        app: face-image-input-api
  template:
    metadata:
      labels:
        app: face-image-input-api
    spec:
      containers:
        - env:
            - name: S3_BUCKET
              valueFrom:
                configMapKeyRef:
                  key: bucket-face-image
                  name: s3-bucket
            - name: KAFKA_TOPIC_FACE_IMAGE
              valueFrom:
                configMapKeyRef:
                  key: KAFKA_TOPIC_FACE_IMAGE_INPUT
                  name: kafka-topic
            - name: LOG_LEVEL
              value: debug
          envFrom:
            - configMapRef:
                name: mysql-connections
            - configMapRef:
                name: kafka-endpoint
            - configMapRef:
                name: s3-endpoint
            - configMapRef:
                name: s3-key
          image: supakornbabe/spai-face-image-input-api:dev-b9f62f3
          imagePullPolicy: Always
          name: face-image-input-api
          ports:
            - containerPort: 80
              protocol: TCP
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
