apiVersion: v1
kind: Service
metadata:
  name: face-image-input-api-service
  labels:
    app: face-image-input-api
spec:
  ports:
  - protocol: TCP
    port: 80
  selector:
    app: face-image-input-api
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: face-image-input-api
  name: face-image-input-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: face-image-input-api
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: face-image-input-api
    spec:
      containers:
      - image: supakornbabe/spai-face-image-input-api:dev-c97e0f2
        name: spai-face-image-input-api
        resources: {}